version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "80:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/survey_db
      - FLASK_ENV=production
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: 