services:
  webapp:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app  # Mounts the current directory to /app in the container for development
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/survey_db # Service name 'mongo' is used as hostname
      - FLASK_DEBUG=1 # Enables Flask debug mode

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db # Persists MongoDB data

volumes:
  mongo-data: 